### ISSUE TITLE
Add feedback command - with GDocs backup

### ISSUE THREAD

**Issue by NumerX** [sirpete/LMAOBot#6]
# Feedback!

## Why it's important
Feedback is really important for a project this large. As of now, the only feedback that we can get is from our support server, which is not ideal. From our sick 7100 servers, we get feedback from one.

## Plans
I found a npm module called [google-spreadsheet-append](https://www.npmjs.com/package/google-spreadsheet-append) which would let us add rows to a google spreadsheet (**Surprisingly**). Using that, it should not be difficult to setup a feedback command, taking arguments, and shoving them inside the document.

------

![Feedback command sample img](https://i.imgur.com/NhKwkW5.png)
- [x] Feedback command
<dl>
  <dd><b>Syntax: </b><code>lmao feedback &lt;feedback&gt;</code></dd>
  <dd><b>Response: </b> :info: Thank you for submitting feedback to us!
<b>PLEASE NOTE:</b> Abusing the command will result in a permanent ban from ever using it again!</dd>
</dl>

- [x] ~~Synchronistion to google docs~~ **#feedback channel based system.**
Replaced by a discord channel based feedback system. It is done. #8 
------

![Banfeedback command sample](https://i.imgur.com/m5JgWv3.png)
- [ ] Developer only banfeedback command
<dl>
  <dd><b>Syntax: </b><code>lmao banfeedback &lt;userID&gt;</code></dd>
  <dd><b>Response: </b> :info: User banned. </dd>
</dl>

![Unbanfeedback command sample](https://i.imgur.com/YZWjOmZ.png)
- [ ] Developer only unbanfeedback command
<dl>
  <dd><b>Syntax: </b><code>lmao unbanfeedback&lt;userID&gt;</code></dd>
  <dd><b>Response: </b> :info: User unbanned. </dd>
</dl>

**Comment by ClarkThyLord** [comment]
I did something like this for my past bot... but instead of using google api and what not I'd just send msgs to a channel on the bot's support server... which in my opinion would be easiest and best 🤔

**Comment by NumerX** [comment]
@ClarkThyLord The Google API part is already finished, and I prefer it a lot more than just spamming a channel. we can mark it with colors depending on verdict, write notes next to it, and so on...

**Comment by ClarkThyLord** [comment]
right, but the same can be done on discord, reactions and what not, and we'd lose the need to use yet another third party since we'd just have everything in one API that being Dicord :v

**Comment by ClarkThyLord** [comment]
We've discussed privately, and have decided to move forward with Discord based feedback.

https://github.com/sirpete/LMAOBot/pull/7

**Comment by ClarkThyLord** [comment]
I think it would be best if we did a ban/unban command for any and all commands, not just the feedback command. That way we can prevent abuse of the bot on any given command, or in a sever case, prevent usage of bot totally. 🤔

**Comment by NumerX** [comment]
@ClarkThyLord I will implement something like this using a json file structured like this: 
```js
{
  "commands": {
    "feedback": [
      "banned userid"
    ]
  },
  "guilds": ["guildid1","bannedguildid2"],
  "users": ["banneduserfromwholebotid", "..:"]
}
```

**Comment by NumerX** [comment]
from there I can use require to read, and fs to write to the json file on new banned id.

**Comment by NumerX** [comment]
command done #8

**Comment by NumerX** [comment]
I think that the ban system is a completely different issue to tackle, so I am going to close this issue. the ban system is not needed to finish feedback.
